#ifndef _AMC6821_MAP_
#define _AMC6821_MAP_

#define FLAG(BIT) (1<<BIT)
#define NO_FLAG(BIT) (1<<(BIT+8))
#define MOD_FLAGS(REG, FLAGS) ((REG&~(FLAGS>>8))|(FLAGS&0xFF))

#define AMC_DEVICE_ID_REG 		0x3D
#define AMC_DEVICE_ID_DEFAULT 		0x21

#define AMC_COMPANY_ID_REG 		0x3E
#define AMC_COMPANY_ID_DEFAULT 		0x49

#define AMC_CONF1_REG 			0x00
#define AMC_CONF1_RW_IDX 		0
#define AMC_CONF1_DEFAULT 		0xD4
	#define	THERM_INT_EN		(7)
	#define	FDRC1			(6)
	#define	FDRC0			(5)
	#define	FAN_FAULT_EN		(4)
	#define	PWM_INVERT		(3)
	#define	RPM_INT_EN		(2)
	#define	GLOBAL_INT_EN		(1)
	#define	START_MONITOR		(0)

	#define	O_THERM_INT_EN		(FLAG(THERM_INT_EN))
	#define	O_FDRC1			(FLAG(FDRC1)|NO_FLAG(FDRC0))
	#define	O_FDRC0			(NO_FLAG(FDRC1)|FLAG(FDRC0))
	#define	O_FAN_FAULT_EN		(FLAG(FAN_FAULT_EN))
	#define	O_PWM_INVERT		(FLAG(PWM_INVERT))
	#define	O_RPM_INT_EN		(FLAG(RPM_INT_EN))
	#define	O_GLOBAL_INT_EN		(FLAG(GLOBAL_INT_EN))
	#define	O_START_MONITOR		(FLAG(START_MONITOR))

	#define	O_NO_THERM_INT_EN	(NO_FLAG(THERM_INT_EN))
	#define	O_NO_FDRC1		(NO_FLAG(FDRC1))
	#define	O_NO_FDRC0		(NO_FLAG(FDRC0))
	#define	O_NO_FAN_FAULT_EN	(NO_FLAG(FAN_FAULT_EN))
	#define	O_NO_PWM_INVERT		(NO_FLAG(PWM_INVERT))
	#define	O_NO_RPM_INT_EN		(NO_FLAG(RPM_INT_EN))
	#define	O_NO_GLOBAL_INT_EN	(NO_FLAG(GLOBAL_INT_EN))
	#define	O_NO_START_MONITOR	(NO_FLAG(START_MONITOR))

#define AMC_CONF2_REG 			0x01
#define AMC_CONF2_RW_IDX 		1
#define AMC_CONF2_DEFAULT 		0x3D
	#define	RESET			(7)
	#define	LPSV_INT_EN		(6)
	#define	RT_INT_EN		(5)
	#define	LT_INT_EN		(4)
	#define	REMOTE_FAIL_INT_EN	(3)
	#define	TACH_EN			(2)
	#define	TACH_MODE		(1)
	#define	PWM_OUT_EN		(0)

	#define	O_RESET			(FLAG(RESET))
	#define	O_LPSV_INT_EN		(FLAG(LPSV_INT_EN))
	#define	O_RT_INT_EN		(FLAG(RT_INT_EN))
	#define	O_LT_INT_EN		(FLAG(LT_INT_EN))
	#define	O_REMOTE_FAIL_INT_EN	(FLAG(REMOTE_FAIL_INT_EN))
	#define	O_TACH_EN		(FLAG(TACH_EN))
	#define	O_TACH_MODE		(FLAG(TACH_MODE))
	#define	O_PWM_OUT_EN		(FLAG(PWM_OUT_EN))

	#define	O_NO_RESET		(NO_FLAG(RESET))
	#define	O_NO_LPSV_INT_EN	(NO_FLAG(LPSV_INT_EN))
	#define	O_NO_RT_INT_EN		(NO_FLAG(RT_INT_EN))
	#define	O_NO_LT_INT_EN		(NO_FLAG(LT_INT_EN))
	#define	O_NO_REMOTE_FAIL_INT_EN	(NO_FLAG(REMOTE_FAIL_INT_EN))
	#define	O_NO_TACH_EN		(NO_FLAG(TACH_EN))
	#define	O_NO_TACH_MODE		(NO_FLAG(TACH_MODE))
	#define	O_NO_PWM_OUT_EN		(NO_FLAG(PWM_OUT_EN))

#define AMC_CONF3_REG 			0x3F
#define AMC_CONF3_RW_IDX 		2
#define AMC_CONF3_DEFAULT 		0x82
	#define	THERM_FAN_EN		(7)

	#define	O_THERM_FAN_EN		(FLAG(THERM_FAN_EN))

	#define	O_NO_THERM_FAN_EN	(NO_FLAG(THERM_FAN_EN))

#define AMC_CONF4_REG 			0x04
#define AMC_CONF4_RW_IDX 		3
#define AMC_CONF4_DEFAULT 		0x08
	#define	PULSE_NUMBER		(6)
	#define	TACH_FAST		(5)
	#define	OVR_PIN_EN		(4)

	#define	O_PULSE_NUMBER		(FLAG(PULSE_NUMBER))
	#define	O_TACH_FAST		(FLAG(TACH_FAST))
	#define	O_OVR_PIN_EN		(FLAG(OVR_PIN_EN))

	#define	O_NO_PULSE_NUMBER	(NO_FLAG(PULSE_NUMBER))
	#define	O_NO_TACH_FAST		(NO_FLAG(TACH_FAST))
	#define	O_NO_OVR_PIN_EN		(NO_FLAG(OVR_PIN_EN))

#define AMC_STATUS1_REG 		0x02
#define AMC_STATUS1_DEFAULT 		0x00
	#define	LT_LOW			(7)
	#define	LT_HIGH			(6)
	#define	RT_FAIL			(5)
	#define	RT_OVER_THERM		(4)
	#define	RT_LOW			(3)
	#define	RT_HIGH			(2)
	#define	FAN_SLOW		(1)
	#define	FAN_FAST		(0)

#define AMC_STATUS2_REG 		0x03
#define AMC_STATUS2_DEFAULT 		0x00
	#define	THERM_INPUT		(7)
	#define	LT_OVER_THERM		(6)
	#define	LT_BELOW_THERM		(5)
	#define	LT_OVER_CRIT		(4)
	#define	RT_OVER_CRIT		(3)

#define AMC_TEMP_DATA_LBYTE_REG		0x06
#define AMC_TEMP_DATA_LBYTE_DEFAULT	0x00
	#define LOCAL_TEMP_LBITS	(5)
	#define REMOTE_TEMP_LBITS	(0)

#define AMC_LOCAL_TEMP_DATA_HBYTE_REG		0x0A
#define AMC_LOCAL_TEMP_DATA_HBYTE_DEFAULT	0x80

#define AMC_REMOTE_TEMP_DATA_HBYTE_REG		0x0B
#define AMC_REMOTE_TEMP_DATA_HBYTE_DEFAULT	0x80

#define AMC_LOCAL_HIGH_TEMP_LIMIT_REG		0x14
#define AMC_LOCAL_HIGH_TEMP_LIMIT_RW_IDX	4
#define AMC_LOCAL_HIGH_TEMP_LIMIT_DEFAULT	0x3C

#define AMC_LOCAL_LOW_TEMP_LIMIT_REG		0x15
#define AMC_LOCAL_LOW_TEMP_LIMIT_RW_IDX		5
#define AMC_LOCAL_LOW_TEMP_LIMIT_DEFAULT	0x00

#define AMC_LOCAL_THERM_LIMIT_REG		0x16
#define AMC_LOCAL_THERM_LIMIT_RW_IDX		6
#define AMC_LOCAL_THERM_LIMIT_DEFAULT		0x46

#define AMC_REMOTE_HIGH_TEMP_LIMIT_REG		0x18
#define AMC_REMOTE_HIGH_TEMP_LIMIT_RW_IDX	7
#define AMC_REMOTE_HIGH_TEMP_LIMIT_DEFAULT	0x50

#define AMC_REMOTE_LOW_TEMP_LIMIT_REG		0x19
#define AMC_REMOTE_LOW_TEMP_LIMIT_RW_IDX	8
#define AMC_REMOTE_LOW_TEMP_LIMIT_DEFAULT	0x00

#define AMC_REMOTE_THERM_LIMIT_REG		0x1A
#define AMC_REMOTE_THERM_LIMIT_RW_IDX		9
#define AMC_REMOTE_THERM_LIMIT_DEFAULT		0x64

#define AMC_LOCAL_CRIT_LIMIT_REG	0x1B
#define AMC_LOCAL_CRIT_LIMIT_RW_IDX	10
#define AMC_LOCAL_CRIT_LIMIT_DEFAULT	0x50

#define AMC_PSV_TEMP_REG		0x1C
#define AMC_PSV_TEMP_RW_IDX		11
#define AMC_PSV_TEMP_DEFAULT		0x00

#define AMC_REMOTE_CRIT_LIMIT_REG	0x1D
#define AMC_REMOTE_CRIT_LIMIT_RW_IDX	12
#define AMC_REMOTE_CRIT_LIMIT_DEFAULT	0x69

#define AMC_FAN_CHARACTERISTICS_REG	0x20
#define AMC_FAN_CHARACTERISTICS_RW_IDX	13
#define AMC_FAN_CHARACTERISTICS_DEFAULT	0x1D
	#define FAN_SPIN_DISABLED	(7)
	#define PWM_FREQ_SETTING	(3)
	#define SPIN_UP_TIME_SETTING	(0)

#define AMC_DCY_LOW_TEMP_REG		0x21
#define AMC_DCY_LOW_TEMP_RW_IDX		14
#define AMC_DCY_LOW_TEMP_DEFAULT	0x55

#define AMC_DCY_REG			0x22
#define AMC_DCY_RW_IDX			15
#define AMC_DCY_DEFAULT			0x55

#define AMC_DCY_RAMP_REG		0x23
#define AMC_DCY_RAMP_RW_IDX		16
#define AMC_DCY_RAMP_DEFAULT		0x52
	#define RAMP_ENABLE		(7)
	#define DCY_ADJUSTMENT_STEP	(5)
	#define DCY_UPDATE_RATE		(2)
	#define DCY_ADJUSTMENT_THRESHOLD (0)

#define AMC_LOCAL_TEMP_FAN_CONTROL_REG		0x24
#define AMC_LOCAL_TEMP_FAN_CONTROL_RW_IDX	17
#define AMC_LOCAL_TEMP_FAN_CONTROL_DEFAULT	0x41
	#define LOW_LOCAL_TEMP		(3)
	#define SLOPE_LOCAL_TEMP	(0)

#define AMC_REMOTE_TEMP_FAN_CONTROL_REG		0x25
#define AMC_REMOTE_TEMP_FAN_CONTROL_RW_IDX	18
#define AMC_REMOTE_TEMP_FAN_CONTROL_DEFAULT	0x61
	#define LOW_REMOTE_TEMP		(3)
	#define SLOPE_REMOTE_TEMP	(0)

#define AMC_TACH_DATA_LBYTE_REG		0x08
#define AMC_TACH_DATA_LBYTE_DEFAULT	0x00

#define AMC_TACH_DATA_HBYTE_REG		0x09
#define AMC_TACH_DATA_HBYTE_DEFAULT	0x00

#define AMC_TACH_LOW_LIMIT_LBYTE_REG		0x10
#define AMC_TACH_LOW_LIMIT_LBYTE_RW_IDX		19
#define AMC_TACH_LOW_LIMIT_LBYTE_DEFAULT	0xFF

#define AMC_TACH_LOW_LIMIT_HBYTE_REG		0x11
#define AMC_TACH_LOW_LIMIT_HBYTE_RW_IDX		20
#define AMC_TACH_LOW_LIMIT_HBYTE_DEFAULT	0xFF

#define AMC_TACH_HIGH_LIMIT_LBYTE_REG		0x12
#define AMC_TACH_HIGH_LIMIT_LBYTE_RW_IDX	21
#define AMC_TACH_HIGH_LIMIT_LBYTE_DEFAULT	0x00

#define AMC_TACH_HIGH_LIMIT_HBYTE_REG		0x13
#define AMC_TACH_HIGH_LIMIT_HBYTE_RW_IDX	22
#define AMC_TACH_HIGH_LIMIT_HBYTE_DEFAULT	0x00

#define AMC_TACH_SETTING_LBYTE_REG	0x1E
#define AMC_TACH_SETTING_LBYTE_RW_IDX	23
#define AMC_TACH_SETTING_LBYTE_DEFAULT	0xFF

#define AMC_TACH_SETTING_HBYTE_REG	0x1F
#define AMC_TACH_SETTING_HBYTE_RW_IDX	24
#define AMC_TACH_SETTING_HBYTE_DEFAULT	0xFF

#define AMC_N_RO_REGS	9
#define AMC_N_RW_REGS	25

#endif
